# Use an Ubuntu 18.04 base for our staging server 
FROM ubuntu:18.04

# Update package list and install python3 and aria2
RUN apt-get update && \
    apt-get install -y python3 aria2

# Download a file using aria2
RUN aria2c -d /root/downloads -o example-file.zip "http://example.com/file.zip"

# Install python3 http server (if you want to serve files)
RUN echo '<b>some html</b>' > hello.html
RUN echo '<b>another file</b>' > another.html

# Expose port 80 for the staging server to be accessible
EXPOSE 80

# Start the Python HTTP server in the background
CMD python3 -m http.server 80
