---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install tget
          command: npm install -g tget
      - run:
          name: Download torrent
          command: tget your-torrent-file.torrent --output ./downloads/
workflows:
  version: 2
  build:
    jobs:
      - build
