name: Torrent Download with Aria2 (No Seeding)

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Install Aria2
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2

      - name: Create Directory for Downloads
        run: |
          mkdir -p ~/torrent_downloads  # Create a download directory

      - name: Download Torrent
        id: download_torrent  # Add an ID to access in later steps
        run: |
          echo "Starting torrent download without seeding..."
          aria2c --dir=~/torrent_downloads --seed-time=0 "magnet:?xt=urn:btih:119C1E5EBECBA1F680DDA572B8FBB7F6DB6D95E1&dn=Arcane.S02E01.1080p.WEB.H264-SuccessfulCrab%5BTGx%5D&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.birkenwald.de%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentor.org%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fuploads.gamecoast.net%3A6969%2Fannounce&tr=https%3A%2F%2Ftracker.foreverpirates.co%3A443%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce"

      - name: Verify Downloaded Files
        run: |
          echo "Verifying downloaded files..."
          ls -la ~/torrent_downloads  # List files in the download directory

      - name: Upload Downloaded Files
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-files
          path: ~/torrent_downloads/*  # Upload all files in the download directory
