name: Torrent Download with Transmission

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Install Transmission CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y transmission-cli

      - name: Create Directory for Downloads
        run: |
          mkdir -p ~/torrent_downloads  # Create a download directory

      - name: Download Torrent
        run: |
          echo "Starting torrent download..."
          transmission-cli -w ~/torrent_downloads "magnet:?xt=urn:btih:3716A56E7EEBED5B721CB8F6C98F3BF44E6946A2&tr=udp%3A%2F%2Ftracker.bitsearch.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.uw0.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&dn=%5BBitsearch.to%5D+13+Ghosts+(1960)+%5BBluRay%5D+%5B720p%5D+%5BYTS.LT%5D"
          
          # Optional: Sleep to allow some downloads to initiate.
          sleep 3600  # Adjust the duration as needed for your downloads to complete

      - name: List Downloaded Files
        run: |
          echo "Downloaded files:"
          ls ~/torrent_downloads  # List files in the download directory

      # Optionally, clean up or stop the download if needed
      - name: Clean Up
        run: |
          # There's no direct stop command in transmission-cli, so this step can be adjusted
          echo "Optionally stops any ongoing torrents if needed."
